services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - tm-network

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@local.com
            PGADMIN_DEFAULT_PASSWORD: admin

        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - tm-network

    backend:
        build: ./backend
        ports:
            - "4000:4000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            PORT: 4000
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - db
        networks:
            - tm-network

    frontend:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend
        networks:
            - tm-network

volumes:
    db_data:
    frontend_node_modules:
networks:
    tm-network:
